#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Bind the offline consumer to preserved node-generated bytes and fixtures."""

import argparse
import base64
import hashlib
import importlib.util
import json
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent


def load(name):
    spec = importlib.util.spec_from_file_location("balance_observation_" + name, HERE / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


consumer = load("observe_balance")
oracle = load("check")


def text_identifier(prefix, raw):
    # Fixture conversion only. Proof paths and keys remain the original Go
    # observations; this encoder does not manufacture any proof or root.
    symbols = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"
    bits = "".join(format(b, "08b") for b in raw)
    words = [int(bits[n:n + 5], 2) for n in range(0, len(bits), 5)]
    expanded = [ord(c) // 32 for c in prefix] + [0] + [ord(c) % 32 for c in prefix]
    check = 1
    for word in expanded + words + [0] * 6:
        high = check // (1 << 25)
        check = ((check % (1 << 25)) * 32) ^ word
        for mask, polynomial in zip((1, 2, 4, 8, 16),
                                   (0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3)):
            if high & mask:
                check ^= polynomial
    check ^= 1
    checksum = [(check >> shift) & 31 for shift in (25, 20, 15, 10, 5, 0)]
    return prefix + "1" + "".join(symbols[n] for n in words + checksum)


def fixture_selection(key, root, present, value, height, header_hash):
    assert len(key) == 32 and key[0] == key[21] == 3
    return {"kind": consumer.SELECTION_KIND, "profile": consumer.PROFILE,
            "genesis_hash": hashlib.sha256(b"unsigned-balance-fixture-genesis").hexdigest(),
            "context_pin": hashlib.sha256(b"unsigned-balance-fixture-context").hexdigest(),
            "header": {"version": 3, "chain_identifier": 99, "height": height,
                       "hash": header_hash, "state_root": root},
            "address": text_identifier("z", key[1:21]),
            "token_standard": text_identifier("zts", key[22:]), "request_id": "balance-fixture",
            "claim": {"present": present, "amount": str(int.from_bytes(value, "big"))}}


def fixture_response(root, present, value, proof):
    return {"jsonrpc": "2.0", "id": "balance-fixture", "result": {
            "root": root, "value": base64.b64encode(value).decode("ascii") if present else None,
            "proof": base64.b64encode(proof).decode("ascii")}}


def preserved_cases():
    raw, corpus = oracle.read_corpus(HERE / "testdata/candidate-v3-balances.json")
    oracle.check_corpus(corpus)
    cases = []
    for row in corpus["proofs"]:
        if row["domain"] != "balance":
            continue
        assert row["node_result"] == "match"
        key, value, proof = (bytes.fromhex(row[k]) for k in ("raw_key", "value", "proof"))
        chosen = fixture_selection(key, row["root"], row["present"], value, 17,
                                   hashlib.sha256(b"unsigned-balance-primitive-header").hexdigest())
        response = fixture_response(row["root"], row["present"], value, proof)
        cases.append(("primitive/" + row["name"], chosen, response,
                      "research_balance_bound" if len(value) == 33 else None, key))
    applier = load("check_applier")
    _, corpus = oracle.read_corpus(HERE / "testdata/candidate-l1-applier.json")
    applier.check_corpus(corpus)
    for checkpoint in corpus["checkpoints"]:
        if checkpoint["height"] == 0:
            continue  # Zero-height RPC queries are deliberately unsupported.
        for row in checkpoint["observations"]:
            if row["name"] not in ("balance-a", "balance-b"):
                continue
            key, value, proof = (bytes.fromhex(row[k]) for k in ("key", "value", "proof"))
            chosen = fixture_selection(key, checkpoint["root"], row["present"], value,
                                       checkpoint["height"], checkpoint["hash"])
            cases.append(("applier/" + checkpoint["name"] + "/" + row["name"], chosen,
                          fixture_response(checkpoint["root"], row["present"], value, proof), None, key))
    assert len(cases) == 18
    return cases


def check_observations():
    observations = []
    for name, chosen, response, error, key in preserved_cases():
        try:
            request = consumer.prepare_request(chosen)
            assert request == {"jsonrpc": "2.0", "id": chosen["request_id"], "method": "ledger.getProof",
                               "params": [chosen["header"]["height"], base64.b64encode(key).decode("ascii")]}
            report = consumer.observe(chosen, response)
        except consumer.Refusal as failure:
            assert str(failure) == error
            observations.append({"name": name, "candidate_observation": "REFUSED", "error": error})
        else:
            assert error is None
            assert report["candidate_observation"] == "MATCH" and report["proven"] == []
            assert report["consumer_result"] == "REFUSED" and not report["header_authentication_executed"]
            assert not report["production_state_value_accepted"]
            assert {"present": report["present"], "amount": report["amount"]} == chosen["claim"]
            observations.append({"name": name, "candidate_observation": "MATCH",
                                 "present": report["present"], "amount": report["amount"], "proof_bytes": report["proof_bytes"]})
    selection_path = HERE / "testdata/balance-observation-selection.json"
    response_path = HERE / "testdata/balance-observation-response.json"
    selected_raw, selected = consumer.read_document(selection_path, consumer.MAX_SELECTION)
    response_raw, response = consumer.read_document(response_path, consumer.MAX_RESPONSE)
    wire = json.loads((HERE / "testdata/candidate-state-proof-wire.json").read_bytes())
    row = next(r for r in wire["binding_cases"] if r["name"] == "stored-zero")
    expected_selection = fixture_selection(bytes.fromhex(row["raw_key"]), row["root"], True,
                                          bytes.fromhex(row["value_hex"]), 17,
                                          hashlib.sha256(b"unsigned-balance-example-header").hexdigest())
    assert selected == expected_selection
    assert response == {"jsonrpc": "2.0", "id": "balance-fixture", "result": json.loads(row["wire"])}
    example = consumer.observe(selected, response)
    assert example["candidate_observation"] == "MATCH" and example["present"] and example["amount"] == "0"
    inputs = ["candidate-v3-balances.json", "candidate-l1-applier.json", "candidate-state-proof-wire.json",
              "balance-observation-selection.json", "balance-observation-response.json"]
    pins = {name: hashlib.sha256((HERE / "testdata" / name).read_bytes()).hexdigest() for name in inputs}
    fingerprint = hashlib.sha256(json.dumps(pins, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    return {"kind": "read-only-candidate-balance-observation-conformance", "corpus_sha256": fingerprint,
            "input_files_sha256": pins, "preserved_node_observations": 18, "candidate_matches": 17,
            "research_policy_refusals": 1, "example_matches": 1,
            "observations": observations, "selection_sha256": hashlib.sha256(selected_raw).hexdigest(),
            "response_sha256": hashlib.sha256(response_raw).hexdigest(),
            "new_node_execution": False, "network_transport_executed": False,
            "header_authentication_executed": False, "consumer_result": "REFUSED",
            "production_state_value_accepted": False}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-revision", default="unspecified")
    args = parser.parse_args()
    assert args.source_revision == "unspecified" or re.fullmatch("[0-9a-f]{40}", args.source_revision)
    print(json.dumps(check_observations() | {"source_revision": args.source_revision}, sort_keys=True))


if __name__ == "__main__":
    main()
